CREATE TABLE IF NOT EXISTS retros (
    retroId BINARY(16) NOT NULL PRIMARY KEY,
    retroName VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS retroEvents (
    eventId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    retroId BINARY(16) NOT NULL,
    retroVersion BIGINT UNSIGNED NOT NULL DEFAULT 1,
    eventData MEDIUMTEXT NOT NULL,
    occurredAt DATETIME NOT NULL,
    UNIQUE KEY (retroId, retroVersion)
);